import { useEffect, useRef, useState, type ReactNode } from 'react';
import { useReducedMotion } from 'motion/react';
import { ArrowDownRight, ArrowLeft, ArrowRight, Search, X } from 'lucide-react';
import { pageComponents } from './page-routes';
import searchPages from './search-data.json';

const nav = [['About','about.html'],['Team','team.html'],['Schedule','schedule.html'],['Resources','resources.html'],['Coding','datascience.html'],['FAQ','faq.html']];
const primaryNav = nav;
const more = [['For schools','schools.html'],['For students','researchers.html'],['For judges','judges.html'],['Register','register.html'],['Student registration','student-signup.html'],['Volunteer registration','volunteer-signup.html'],['Open source','opensource.html'],['Python','python.html'],['RStudio','rstudio.html']];
const facts = [['Participation','100% free'],['Who can join','All middle & high school students'],['When','April 24th, 2027'],['Where','Exeter, NH + online']];
const guidance = [
  {title:'Begin with curiosity.',text:'No prior research experience is required. Start with a biological question, then use the resources to make it specific and workable.',href:'resources.html#drylab',image:'/images/Planning/Screenshot 2026-09-10 at 6.03.22 PM.png',alt:'Student reading a research paper in a laboratory'},
  {title:'Learn at your own pace.',text:'Lectures and materials are asynchronous. Most students spend 1–2 hours per week throughout the year.',href:'schools.html',image:'/images/Data Analysis/R Studio.png',alt:'Student using R Studio for data analysis'},
  {title:'Make the evidence clear.',text:'Document your methods, explain your results, and distinguish your findings from the questions still open.',href:'resources.html#presenting',image:'/images/Poster/Luke Poster.jpeg',alt:'Student research poster about fungal enzyme inhibitors'}
];
function ArrowLink({href,children,className=''}:{href:string;children:ReactNode;className?:string}) { return <a className={`button ${className}`} href={href}><span>{children}</span><ArrowDownRight size={18}/></a>; }

function Header({page}:{page:string}) {
  const search=useRef<HTMLDialogElement>(null);const menu=useRef<HTMLDetailsElement>(null);
  const[query,setQuery]=useState('');const[dark,setDark]=useState(false);const[scrolled,setScrolled]=useState(false);
  useEffect(()=>{
    const media=window.matchMedia('(prefers-color-scheme: dark)');let saved:string|null=null;
    try{saved=localStorage.getItem('ebs-theme');}catch{/* Storage is optional. */}
    const apply=(value:boolean)=>{setDark(value);document.documentElement.dataset.theme=value?'dark':'light';};
    apply(saved==='dark'||(saved!=='light'&&media.matches));
    const change=()=>{try{if(localStorage.getItem('ebs-theme'))return;}catch{/* Use OS preference. */}apply(media.matches);};
    const scroll=()=>setScrolled(window.scrollY>40);
    const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&menu.current?.open){menu.current.open=false;menu.current.querySelector('summary')?.focus();}};
    media.addEventListener('change',change);window.addEventListener('scroll',scroll,{passive:true});document.addEventListener('keydown',key);scroll();
    return()=>{media.removeEventListener('change',change);window.removeEventListener('scroll',scroll);document.removeEventListener('keydown',key);};
  },[]);
  function toggleTheme(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('ebs-theme',next?'dark':'light');}catch{/* Local theme remains usable. */}}
  const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  const results=searchPages.map(({title,url,description})=>({title,url,score:terms.reduce((sum,term)=>sum+(title.toLowerCase()===term?12:title.toLowerCase().includes(term)?7:(url+' '+description).toLowerCase().includes(term)?3:0),0)})).filter(row=>!terms.length||row.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,8);
  return <><header className={`site-header ${page==='index.html'&&!scrolled?'on-media':''}`}><a className="skip" href="#main">Skip to content</a><a className="wordmark" href="index.html" aria-label="Exeter Biology Symposium home">EBS</a><nav className="desktop-nav" aria-label="Main navigation">{primaryNav.map(([label,href])=><a key={href} href={href} aria-current={page===href?'page':undefined}>{label}</a>)}<button className="nav-search" type="button" aria-label="Search EBS" aria-haspopup="dialog" onClick={()=>search.current?.showModal()}><Search size={18}/></button></nav><div className="header-right"><a href="faq.html#contact">Contact</a><button className="header-theme" type="button" onClick={toggleTheme}>Use {dark?'light':'dark'} theme</button><ArrowLink href="register.html">Register</ArrowLink></div><details className="site-menu" ref={menu}><summary>Menu <span aria-hidden="true">☰</span></summary><div className="menu-panel"><nav aria-label="All pages">{[...primaryNav,...more].map(([label,href])=><a href={href} key={href}>{label}<ArrowDownRight size={17}/></a>)}</nav><div className="menu-tools"><button type="button" onClick={()=>{if(menu.current)menu.current.open=false;search.current?.showModal();}}>Search EBS <Search size={17}/></button><button type="button" onClick={toggleTheme}>Use {dark?'light':'dark'} theme</button></div></div></details></header><dialog ref={search} className="search-dialog" aria-labelledby="search-title" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();search.current?.close();}}}><form method="dialog"><button aria-label="Close search"><X size={22}/></button></form><h2 id="search-title">Search EBS</h2><label htmlFor="search-input">Page or topic</label><input id="search-input" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Python, schools, registration…"/><p role="status">{results.length} matching pages</p><div className="search-results">{results.map(row=><a href={row.url} key={row.url}>{row.title}<ArrowDownRight size={17}/></a>)}</div></dialog></>;
}
function Footer(){return <footer className="site-footer"><div className="footer-top"><div><p style={{fontSize:'1.5rem',fontWeight:600}}>Exeter Biology Symposium</p><p>A student-run research symposium.</p></div><div><p>Explore</p>{primaryNav.map(([label,href])=><a href={href} key={href}>{label}</a>)}</div><div><p>Take part</p>{more.slice(0,7).map(([label,href])=><a href={href} key={href}>{label}</a>)}</div><div><p>Get in touch</p><a href="mailto:exeterbiologysymposium@gmail.com">exeterbiologysymposium@gmail.com</a><p>April 24th, 2027</p></div></div><div className="footer-wordmark" aria-hidden="true">EBS</div><div className="footer-bottom"><span>© 2026 Exeter Biology Symposium</span><span>Organized by the Genetics and Biotech Club.</span><a href="#main">Back to top ↑</a></div></footer>;}
function Hero(){
  const[active,setActive]=useState(0);const[paused,setPaused]=useState(false);const reduced=useReducedMotion();
  useEffect(()=>{if(paused||reduced)return;const timer=setInterval(()=>setActive(value=>(value+1)%facts.length),8000);return()=>clearInterval(timer);},[paused,reduced]);
  return <section className="home-hero"><picture className="hero-picture"><img className="hero-image" src="/images/team/ebs-team-broad-institute-1920.jpg" srcSet="/images/team/ebs-team-broad-institute-480.jpg 480w, /images/team/ebs-team-broad-institute-960.jpg 960w, /images/team/ebs-team-broad-institute-1440.jpg 1440w, /images/team/ebs-team-broad-institute-1920.jpg 1920w" sizes="100vw" alt="EBS students visiting the Broad Institute" fetchPriority="high"/></picture><div className="hero-shade"/><div className="hero-facts" onMouseEnter={()=>setPaused(true)} onFocusCapture={()=>setPaused(true)}><span>{facts[active][0]}</span><strong>{facts[active][1]}</strong><div className="fact-controls">{facts.map(([label],index)=><button type="button" key={label} aria-label={`Show ${label}`} aria-pressed={index===active} onClick={()=>{setActive(index);setPaused(true);}}><span/></button>)}<button className="autoplay-control" type="button" onClick={()=>setPaused(value=>!value)}>{paused?'Play':'Pause'}</button></div></div><div className="hero-bottom"><div className="hero-copy"><h1 style={{fontSize:'clamp(2.75rem,8vw,6.5rem)',lineHeight:1.02}}>Exeter Biology Symposium</h1><p style={{fontSize:'clamp(1.15rem,2.4vw,1.6rem)',fontWeight:500}}>Biology research.<br/>Led by students.<br/>Open to everyone.</p><p>100% free for all middle and high school students.<br/>Learn, investigate, and present—in person or online.</p><a className="school-link" href="schools.html">Register your school ↗</a></div><ArrowLink href="student-signup.html" className="media-button">Register as a student</ArrowLink></div></section>;
}
function Guidance(){const[active,setActive]=useState(0);const item=guidance[active];return <section className="guidance-section"><h2>What makes student research possible?</h2><div className="guidance-grid"><div className="guidance-copy"><div aria-live="polite"><h3>{item.title}</h3><p>{item.text}</p><ArrowLink href={item.href}>Learn more</ArrowLink></div></div><div className="guidance-media"><figure className="cover-media"><img src={item.image} alt={item.alt} loading="lazy"/></figure><div className="rail-controls"><button type="button" aria-label="Previous guidance" onClick={()=>setActive((active+guidance.length-1)%guidance.length)}><ArrowLeft size={18}/></button><span aria-live="polite">{active+1} / {guidance.length}</span><button type="button" aria-label="Next guidance" onClick={()=>setActive((active+1)%guidance.length)}><ArrowRight size={18}/></button></div><div className="guidance-tabs" aria-label="Guidance topics">{guidance.map((entry,index)=><button key={entry.title} type="button" aria-pressed={index===active} onClick={()=>setActive(index)}><span>0{index+1}</span>{entry.title}</button>)}</div></div></div></section>;}
const steps=['Ask a question.','Find the evidence.','Make an analysis.','Share what it shows.'];
function Story(){const container=useRef<HTMLElement>(null);const[active,setActive]=useState(0);const reduced=useReducedMotion();
  useEffect(()=>{if(reduced)return;let frame=0;const update=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const box=container.current?.getBoundingClientRect();if(box){const progress=Math.max(0,Math.min(.999,-box.top/(box.height-innerHeight)));setActive(Math.floor(progress*4));}});};window.addEventListener('scroll',update,{passive:true});update();return()=>{window.removeEventListener('scroll',update);cancelAnimationFrame(frame);};},[reduced]);
  return <section className="story-sequence" ref={container}><div className="story-sticky"><h2>{steps[active]}</h2><ol>{steps.map((step,index)=><li key={step} className={active===index?'is-active':''}><button type="button" aria-pressed={active===index} onClick={()=>{setActive(index);if(!reduced&&container.current){const top=container.current.getBoundingClientRect().top+scrollY;window.scrollTo({top:top+(index+.05)*(container.current.offsetHeight-innerHeight)/4,behavior:'instant'});}}}><span>0{index+1}</span>{step}</button></li>)}</ol><a href="resources.html">Explore the resources <ArrowDownRight size={18}/></a></div></section>;}
function HomeFaq(){return <section className="home-faq"><div className="section-introduction"><h2>Before you begin.</h2><a href="faq.html">All questions <ArrowDownRight size={18}/></a></div><div className="home-faq-list">{[['Who can participate?','All middle and high school students are welcome. No prior research experience is required.'],['What does it cost?','Participation is 100% free. Students cover their own travel costs; online presentation is available.'],['How much time will I need?','Most students spend 1–2 hours per week throughout the year. Lectures and materials can be completed asynchronously.'],['How do I register?','Register as a student, school, volunteer, or judge. Each application opens in Google Forms.']].map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>;}
function Closing(){return <section className="closing-scene"><img src="/images/Genetics Club Photos/GeneticsClubBoston_3.jpg" alt="Students exploring science exhibits" loading="lazy"/><div><p className="eyebrow">April 24th, 2027</p><h2>Your question.<br/>Your research.<br/>Your place here.</h2><ArrowLink href="register.html" className="media-button">Take part in EBS</ArrowLink></div></section>;}
function Home(){return <div className="home-page"><Hero/><Guidance/><Story/><section className="mission-split"><h2 className="mission-label">Why EBS exists</h2><div><h2>Research belongs in the hands of students.</h2><p>EBS brings students together to conduct, present, and discuss original dry-lab biological research. Start with a computer, an internet connection, and a question you want to investigate.</p><ArrowLink href="about.html">About the symposium</ArrowLink></div></section><section className="people-section"><div className="section-introduction"><h2>Students behind<br/>the symposium.</h2><a href="team.html">Meet everyone <ArrowDownRight size={18}/></a></div><div className="people-grid">{[['adrian-chan.jpeg','Adrian Chan'],['reya-satam.jpeg','Reya Satam'],['luke-wang.jpg','Luke Wang']].map(([image,name])=><a href="team.html" key={name}><img src={`/images/team/${image}`} alt={name} loading="lazy"/><span>Co-Head</span><h3>{name}</h3></a>)}</div></section><HomeFaq/><Closing/></div>;}
export function App({page}:{page:string}){
  const Content=pageComponents[page as keyof typeof pageComponents];
  useEffect(()=>{const reveal=()=>{let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}if(!id)return;const target=document.getElementById(id);if(!target)return;let parent=target.closest('details');while(parent){parent.open=true;parent=parent.parentElement?.closest('details')??null;}requestAnimationFrame(()=>{target.scrollIntoView();if(!target.hasAttribute('tabindex'))target.setAttribute('tabindex','-1');target.focus({preventScroll:true});});};reveal();window.addEventListener('hashchange',reveal);return()=>window.removeEventListener('hashchange',reveal);},[page]);
  return <><Header page={page}/><main id="main" tabIndex={-1}>{page==='index.html'?<Home/>:Content?<Content/>:<section className="page-heading"><h1>Page not found</h1><a href="index.html">Return home</a></section>}</main><Footer/></>;
}